# Generated by Django 6.0.6 on 2026-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='sender',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
