# Generated by Django 6.0.6 on 2026-06-15 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0002_alter_product_status_aisubscriptionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_status', models.CharField(choices=[('waiting_for_payment', 'Waiting For Payment'), ('waiting_for_admin', 'Waiting For Admin'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='waiting_for_admin', max_length=30)),
                ('activation_gmail', models.EmailField(blank=True, max_length=254)),
                ('delivery_note', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ai_subscription', to='orders.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='product.aisubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
