# Generated by Django 6.0.6 on 2026-06-15 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_status_aisubscriptionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ai_subscription', 'AI Subscription')], default='ai_subscription', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank'), ('manual', 'Manual')], max_length=20)),
                ('transaction_id', models.CharField(max_length=120)),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('activation_gmail', models.EmailField(blank=True, max_length=254)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.aisubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
